import type { Metadata } from "next";
import ToastProvider from "@/components/toastprovider";
import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Sora:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body className={"container font-sans"}>
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>
    </html>
  );
}
