FROM python:3.12

LABEL maintainer="raza-panjwani"
# Set the working directory in the container
WORKDIR /code
# Install system dependencies required for potential Python packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*


# Install Poetry
RUN pip install poetry

COPY . /ecomweb /code/

# Configuration to avoid creating virtual environments inside the Docker container
RUN poetry config virtualenvs.create false


# Install dependencies including development ones
RUN poetry install

EXPOSE 8000

CMD [ "poetry", "run", "uvicorn", "ecomweb.main:app", "--reload" ]